import { createHttpClient } from './factory';
export { AdapterFactory, AlovaAdapter, AxiosAdapter, BaseAdapter, createAdapter, FetchAdapter, isAdapterAvailable, } from './adapters';
export { HttpClientImpl as HttpClient } from './client';
export { createDevTools, globalDevTools, HttpDevTools, } from './devtools';
export type { DevToolsConfig, RequestRecord, } from './devtools';
export { createHttpEnginePlugin, createHttpPlugin, defaultHttpEnginePlugin, httpPlugin, } from './engine';
export type { HttpEnginePluginOptions } from './engine';
export { createHttpClient } from './factory';
export { withCache, } from './features/cache';
export { createGraphQLClient, GraphQLClient, GraphQLClientError, isGraphQLError, } from './features/graphql';
export type { GraphQLClientConfig, GraphQLError, GraphQLRequestConfig, GraphQLResponse, GraphQLVariables, } from './features/graphql';
export { createMockAdapter, createMockInterceptor, MockAdapter, } from './features/mock';
export type { MockMatcher, MockResponse, MockRule, MockStats, } from './features/mock';
export { withRetry, } from './features/retry';
export { BasicSSEClient, createBasicSSEClient, createSSEClient, SSEClient, SSEStatus, } from './features/sse';
export type { SSEClientConfig, SSEEvent, SSEEventListener, } from './features/sse';
export { createWebSocketClient, WebSocketClient, WebSocketStatus, } from './features/websocket';
export type { WebSocketClientConfig, WebSocketEventListener, WebSocketEventType, WebSocketMessage, } from './features/websocket';
export { authInterceptor, cacheInterceptor, contentTypeInterceptor, createAuthInterceptor, createBaseURLInterceptor, createResponseTimeInterceptor, createRetryInterceptor, errorHandlingInterceptor, errorLoggerInterceptor, InterceptorManagerImpl as InterceptorManager, loggingInterceptor, requestIdInterceptor, requestLoggerInterceptor, responseLoggerInterceptor, retryInterceptor, statusCodeInterceptor, timeoutInterceptor, timestampInterceptor, } from './interceptors';
export type * from './types';
export { assertType, createEnum, createTypedError, deepClone, isArray, isFunction, isNonNull, isNumber, isObject, isString, safeGet, safeGetNested, safeJsonParse, typedEntries, typedFilter, typedKeys, typedMerge, typedValues, wrapPromise, } from './types/utils';
export type { AllowsRequestBody, AllStatusCode, ArrayToUnion, BuildUrlWithParams, ClientErrorStatusCode, DeepMerge, DistributiveOmit, ExtractPathParams, FunctionKeys, FunctionsOnly, IsPromise, NonFunctionKeys, PropertiesOnly, ReadonlyTuple, RequestBodyType, ServerErrorStatusCode, StatusCodeMessages, StrictEnum, SuccessStatusCode, UnionToIntersection, UnwrapPromise, } from './types/utils';
export { buildQueryString, buildURL, combineURLs, createHttpError, delay, ErrorClassifier, generateId, HttpStatus, isAbsoluteURL, isArrayBuffer, isBlob, isFormData, isURLSearchParams, mergeConfig, } from './utils';
export { BatchManager, createBatchManager, } from './utils/batch';
export type { BatchConfig, BatchStats, } from './utils/batch';
export { CacheManager, createCacheManager, createEnhancedCacheManager, createLocalStorage, createMemoryStorage, EnhancedCacheManager, LocalStorageCacheStorage, MemoryCacheStorage, } from './utils/cache';
export type { CacheItemMetadata, CacheStats, EnhancedCacheConfig, EnhancedCacheItem, } from './utils/cache';
export { CancelManager, CancelTokenSource, createCancelTokenSource, createTimeoutCancelToken, globalCancelManager, isCancelError, } from './utils/cancel';
export { ConcurrencyManager, createConcurrencyManager, createDeduplicationKeyGenerator, createDeduplicationManager, createRateLimitManager, DeduplicationKeyGenerator, DeduplicationManager, RateLimitManager, DeduplicationManager as RequestDeduplicator, } from './utils/concurrency';
export type { DeduplicationStats, } from './utils/concurrency';
export type { DeduplicationKeyConfig, } from './utils/concurrency';
export { createDebugInterceptor, createHttpDebugger, DebugLevel, HttpDebugger, } from './utils/debugger';
export type { DebugEvent, DebuggerConfig, PerformanceMetrics as DebugPerformanceMetrics, RequestLog, ResponseLog, } from './utils/debugger';
export { createDownloadChunks, createRangeHeader, DownloadProgressCalculator, formatDownloadSpeed, formatTimeRemaining, getFilenameFromResponse, getFilenameFromURL, getMimeTypeFromFilename, isPreviewableFile, mergeDownloadChunks, parseContentRange, saveFileToLocal, supportsRangeRequests, } from './utils/download';
export { builtinRecoveryStrategies, ErrorAnalyzer, ErrorHandler, ErrorType, RetryManager, TimeoutManager, } from './utils/error';
export type { ErrorRecoveryStrategy, ErrorStats, } from './utils/error';
export { createLogger, devLogger, logger, Logger, LogLevel, } from './utils/logger';
export type { LoggerConfig, } from './utils/logger';
export { createMemoryMonitor, globalMemoryCleaner, globalMemoryMonitor, MemoryCleaner, MemoryMonitor, } from './utils/memory';
export type { MemoryMonitorConfig, MemoryStats, MemoryUsage, } from './utils/memory';
export { createRequestMonitor, defaultMonitor, RequestMonitor, } from './utils/monitor';
export type { MonitorConfig, PerformanceMetrics, PerformanceStats, } from './utils/monitor';
export { ConnectionType, createNetworkInterceptor, createNetworkMonitor, globalNetworkMonitor, NetworkMonitor, NetworkStatus, waitForOnline, } from './utils/network';
export type { NetworkInfo, NetworkMonitorConfig, } from './utils/network';
export { createOfflineQueueManager, OfflineQueueManager, } from './utils/offline';
export type { OfflineQueueConfig, OfflineQueueStats, } from './utils/offline';
export { createRequestPool, defaultPool, RequestPool, } from './utils/pool';
export type { ConnectionInfo, PoolConfig, PoolStats, } from './utils/pool';
export { createPriorityQueue, determinePriority, Priority, PriorityQueue, } from './utils/priority';
export type { PriorityItem, PriorityQueueConfig, PriorityQueueStats, } from './utils/priority';
export { defaultKeyGenerator, generateRequestKey, DeduplicationKeyGenerator as RequestDeduplicationKeyGenerator, } from './utils/request-dedup';
export type { DeduplicationKeyConfig as RequestDeduplicationKeyConfig, } from './utils/request-dedup';
export { createSignatureInterceptor, createSignatureManager, SignatureManager, } from './utils/signature';
export type { SignatureConfig, SignatureResult, } from './utils/signature';
export { createSmartRetryInterceptor, createSmartRetryManager, globalSmartRetryManager, RetryStrategy, SmartRetryManager, } from './utils/smartRetry';
export type { RetryDecision, SmartRetryConfig, } from './utils/smartRetry';
export { consoleExporter, createRequestTracer, createTraceInterceptor, globalTracer, RequestTracer, Span, SpanStatus, SpanType, Trace, } from './utils/trace';
export type { TraceConfig, TraceContext, TraceSpan, TraceTag, } from './utils/trace';
export { createDataTransformer, createDataTransformInterceptor, DataTransformer, globalDataTransformer, nullToUndefined, transformBigInts, transformDates, } from './utils/transformer';
export type { TransformerConfig, } from './utils/transformer';
export { createFileChunks, createFilePreviewURL, createUploadFormData, FileValidationError, formatFileSize, generateFileHash, getFileExtension, isAudioFile, isDocumentFile, isImageFile, isVideoFile, ProgressCalculator, revokeFilePreviewURL, validateFile, } from './utils/upload';
export * from './vue';
/**
 * 创建默认的 HTTP 客户端实例
 */
export declare const http: import("./client").HttpClientImpl;
export default createHttpClient;
